# Generated by Django 2.0.1 on 2018-05-24 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxeador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Ganadas', models.FloatField(max_length=30)),
                ('Natalidad', models.CharField(max_length=30)),
                ('Perdidas', models.CharField(max_length=30)),
                ('Empates', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('Peso', models.FloatField()),
                ('Categoria', models.CharField(max_length=30)),
                ('AtaqueEspecial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('niveldechakra', models.FloatField()),
                ('Rango', models.CharField(max_length=30)),
                ('LugardeOrigen', models.CharField(max_length=30)),
                ('Naturaleza', models.CharField(max_length=30)),
                ('Clan', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DragonBall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Categoria', models.CharField(default='Ninguna', max_length=30)),
                ('LugardeOrigen', models.CharField(max_length=30)),
                ('Fases_evolucion', models.CharField(max_length=30)),
                ('kii', models.FloatField()),
                ('edad', models.FloatField()),
                ('color_piel', models.CharField(max_length=30)),
                ('Punto_debil', models.CharField(max_length=30)),
                ('AtaqueEspecial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('Nombre_Equipo', models.CharField(max_length=30)),
                ('Capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.Capitan')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenChunin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroEquipo', models.FloatField()),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('Equipos', models.ManyToManyField(to='Aplicacion.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Heroe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('superpower', models.CharField(max_length=30)),
                ('color_piel', models.CharField(max_length=30)),
                ('Estatus', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('Clase', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('niveldechakra', models.FloatField()),
                ('LugardeOrigen', models.CharField(max_length=30)),
                ('Naturaleza', models.CharField(max_length=30)),
                ('Clan', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('Armas', models.FloatField()),
                ('ColordePiel', models.CharField(max_length=30)),
                ('AtaqueEspecial', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateTimeField()),
                ('born_city', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('blood', models.CharField(max_length=30)),
                ('status', models.CharField(default='None', max_length=30)),
                ('job', models.CharField(default='None', max_length=30)),
                ('year', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='Genins',
            field=models.ManyToManyField(to='Aplicacion.Ninja'),
        ),
    ]
